### ISSUE TITLE
在非750px设计图中，选择地址的时候滑动距离有问题

### ISSUE THREAD

**Issue by vincent2d** [alanchenchen/vue-address-picker#1]
将代码用到demo中，发现touchMove事件会引发多出来的Y方向距离滑动,如图，选中地址往上滑动后，地址列表向上移动了一段距离，一瞬间就看不到原来选择的辽宁省，这个如何解决呢？[重现de'mo链接](http://yewenxiang.duapp.com/yqws/#/hello)
![gir](https://user-images.githubusercontent.com/19729963/33820784-f787f6cc-de8b-11e7-9d13-15cf6d14192b.gif)

**Comment by alanchenchen** [comment]
这个的确是我这里移动端适配的问题，因为我这里只是简单的动态更改rem，而且设计图为750px，你现在直接在address-picker源码的directives里这样更改即可
``` javascript
    // let r = document.body.getBoundingClientRect().width/7.5;
    let r = Number.parseFloat(document.documentElement.style.fontSize);
```
对于文字偏左的问题，只需要在item类名里面添加居中即可，源码已更新

**Comment by vincent2d** [comment]
非常感谢 ~
