### ISSUE TITLE
address-picker由于touch事件和css3样式兼容问题导致的滑动问题

### ISSUE THREAD

**Issue by jisuz** [alanchenchen/vue-address-picker#3]
你好，Alan Chen,我使用了你的基于vue的address-picker库，遇到了问题，我是新手vue入门，在复制你的代码移植到项目的组件中使用，发现滑动事件失效了，请问怎么排查？

环境是vue2

**Comment by alanchenchen** [comment]
请贴上代码片段，或者可以复现bug的demo网址。最好能把目录结构截图和组件调用代码发一下

**Comment by hengwei-lhm** [comment]
@alanchenchen 有同样的问题 无法滑动

**Comment by alanchenchen** [comment]
@jisuz @hengwei-lhm 是直接都滑动不了吗？我只能大概猜测，是不是你们直接禁止了touch事件，或者是定位层级在底下

**Comment by Yurisa** [comment]
在华为p8手机上，首次渲染无法滑动，但是调试时更改随便一个样式，猜想大概是触发重绘回流，然后就能滑动

**Comment by alanchenchen** [comment]
@Yurisa 以前我做移动端页面兼容的时候，华为兼容性最差。。。你说的这个问题会不会是因为touch事件兼容问题？

**Comment by Yurisa** [comment]
@alanchenchen 很奇怪的一件事情，用这台华为p8的其他浏览器比如chrome或者微信浏览器打开可以滑动，但是因为项目是native内嵌了一个webapp，然后在app中不能滑动。

**Comment by codewuguojie** [comment]
遇到了同样的问题，直接不能滑动了 ，我只是根据需要改了一些样式

**Comment by Yurisa** [comment]
@codewuguojie 你这个改样式是渲染的时候用js改么

**Comment by alanchenchen** [comment]
@Yurisa 个人猜测为app壳子的webview兼容问题 ，我以前也做的是app内嵌页面。这个组件改变位移是通过dom改变的，可能比vue的编译阶段要晚一些，毕竟不是通过prop来改变，而是渲染之后，真实dom改变style样式

**Comment by codewuguojie** [comment]
@Yurisa，不是的，就是在下面的style里面改的

**Comment by alanchenchen** [comment]
@codewuguojie 建议改变vue组件样式，最好根据类名来覆盖，按道理说，更改样式不会影响滚动，请检查下你项目里的root的font-size是否兼容移动端，因为这个组件是根据rem来判断每次滚动位移的。默认取html的font-size作为基础值

**Comment by Yurisa** [comment]
@alanchenchen 有解决方法么

**Comment by alanchenchen** [comment]
@Yurisa 可以把组件源码里指令部分dom的trasnform改为top或者marginTop这种非css3样式来试试.....但是流畅度不敢保证了额。
